In [24]:
#Opportunity Detection
opportunity_keywords = [
    "growth",
    "investment",
    "expansion",
    "renewable",
    "partnership",
    "innovation",
    "ai",
    "automation",
    "new market"
]

def detect_opportunity(text):

    text = text.lower()

    score = sum(
        keyword in text
        for keyword in opportunity_keywords
    )

    return score

In [25]:
import os
import pandas as pd

os.chdir(r"C:\Users\Hima Bindu N\Downloads\NLP")

combined_df = pd.read_csv("processed_dhl_dataset.csv")

print(combined_df.shape)

(314, 5)

In [26]:
#Risk detection
risk_keywords = [
    "tariff",
    "risk",
    "threat",
    "delay",
    "shortage",
    "regulation",
    "competition",
    "disruption"
]

def detect_risk(text):

    text = text.lower()

    score = sum(
        keyword in text
        for keyword in risk_keywords
    )

    return score

In [27]:
#Trend detection
trend_keywords = [
    "ai",
    "automation",
    "electric",
    "battery",
    "sustainability",
    "renewable",
    "digital"
]

def detect_trend(text):

    text = text.lower()

    score = sum(
        keyword in text
        for keyword in trend_keywords
    )

    return score

In [28]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles:")
print(os.listdir())

Current folder:
C:\Users\Hima Bindu N\Downloads\NLP

Files:
['ddgsdhl.ipynb', 'ddgs_dhl.csv', 'dhl_chromadb', 'dhl_dataset.csv', 'dhl_news.json', 'Embeddings.ipynb', 'merged_dhl_dataset.csv', 'merge_data.ipynb', 'Newsapi.ipynb', 'preprocessing.ipynb', 'processed_dhl_dataset.csv', 'Strategic Intelligence Engine.ipynb', 'Supplychain.ipynb', 'supplychaindive_articles.csv']

In [29]:
opportunity_keywords = [
    "growth",
    "investment",
    "expansion",
    "renewable",
    "partnership",
    "innovation",
    "ai",
    "automation",
    "new market"
]

risk_keywords = [
    "tariff",
    "risk",
    "threat",
    "delay",
    "shortage",
    "regulation",
    "competition",
    "disruption"
]

trend_keywords = [
    "ai",
    "automation",
    "electric",
    "battery",
    "sustainability",
    "renewable",
    "digital"
]

def detect_opportunity(text):
    text = str(text).lower()
    return sum(keyword in text for keyword in opportunity_keywords)

def detect_risk(text):
    text = str(text).lower()
    return sum(keyword in text for keyword in risk_keywords)

def detect_trend(text):
    text = str(text).lower()
    return sum(keyword in text for keyword in trend_keywords)

In [30]:
combined_df["opportunity_score"] = (
    combined_df["clean_text"].apply(detect_opportunity)
)

combined_df["risk_score"] = (
    combined_df["clean_text"].apply(detect_risk)
)

combined_df["trend_score"] = (
    combined_df["clean_text"].apply(detect_trend)
)

print("Done")

Done

In [31]:
combined_df[
    ["title", "opportunity_score", "risk_score", "trend_score"]
].head()

,title,opportunity_score,risk_score,trend_score
0,Hormuz halt forces Middle East trade into huge...,1,0,1
1,The World’s Best Tequila—According To The 2026...,0,0,0
2,Property Council 2026 awards: Tauranga’s new M...,0,0,0
3,The Hidden Infrastructure Challenge Behind Ren...,2,0,1
4,DHL Says Clean Energy Technology Is Getting Ha...,0,0,0

In [32]:
#Filter DHL-Relevant Documents
keywords = [
    "dhl",
    "logistics",
    "supply chain",
    "shipping",
    "freight",
    "transport",
    "warehouse",
    "delivery"
]

def is_relevant(text):
    text = str(text).lower()
    return any(k in text for k in keywords)

dhl_df = combined_df[
    combined_df["clean_text"].apply(is_relevant)
]

print("Original:", len(combined_df))
print("Relevant:", len(dhl_df))

Original: 314
Relevant: 235

In [33]:
dhl_df["opportunity_score"] = (
    dhl_df["clean_text"].apply(detect_opportunity)
)

dhl_df["risk_score"] = (
    dhl_df["clean_text"].apply(detect_risk)
)

dhl_df["trend_score"] = (
    dhl_df["clean_text"].apply(detect_trend)
)

C:\Users\Hima Bindu N\AppData\Local\Temp\ipykernel_31724\3422540964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dhl_df["opportunity_score"] = (
C:\Users\Hima Bindu N\AppData\Local\Temp\ipykernel_31724\3422540964.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dhl_df["risk_score"] = (
C:\Users\Hima Bindu N\AppData\Local\Temp\ipykernel_31724\3422540964.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dhl_df["trend_score"] = (

In [34]:
top_opportunities = dhl_df.sort_values(
    "opportunity_score",
    ascending=False
)

top_opportunities[
    ["title", "opportunity_score"]
].head(10)

                                                 title  opportunity_score
56   Fulfillment Services Global Market Analysis Re...                  4
207  Jul 09, 2025: DHL to deploy 1,000+ additional ...                  4
183  DHL & AutoStore™ Expand Global Warehouse Autom...                  4
111  How 8,000 robots are changing work inside logi...                  3
6    Amazon Bets on Lower-Cost Freight as it Opens ...                  2
20   Covenant Logistics Releases 2025 Corporate Soc...                  2
3    The Hidden Infrastructure Challenge Behind Ren...                  2
129  DHL Targets AI-Driven Data Center Boom with U....                  2
187  Meet the robots that keep DHL running - Automa...                  2
125  DHL News Monitoring Service & Press Release Di...                  2

In [35]:
top_risks = dhl_df.sort_values(
    "risk_score",
    ascending=False
)

top_risks[
    ["title", "risk_score"]
].head(10)

                                                 title  risk_score
14   China's global ecommerce push stalls as Iran w...           1
40        Decision: CAC Outcome: DHL e-commerce UK (9)           1
29   As Europe Feels Pressure from Jet Fuel Market,...           1
95   DHL CEO on Tariff Impact, Asia Investments, He...           1
97   DHL Express CEO on leading through disruption ...           1
293  Razor reshapes supply chain to weather Trump-e...           1
8    Former DHL Express Latin America CEO Joakim Th...           0
10   OL INTERNATIONAL HOLDINGS PRESIDENT AND CEO AL...           0
5    Fleet buys Tesla Semi electric trucks after st...           0
3    The Hidden Infrastructure Challenge Behind Ren...           0

In [36]:
top_trends = dhl_df.sort_values(
    "trend_score",
    ascending=False
)

top_trends[
    ["title", "trend_score"]
].head(10)

                                                 title  trend_score
105  DHL Logistics of Things | Insights into the wo...            3
126  DHL targets growing new energy logistics marke...            3
185  The future of operations with automation | DHL...            3
101  May 21, 2026: DHL Supply Chain Breaks Ground o...            2
111  How 8,000 robots are changing work inside logi...            2
155  DHL Supply Chain builds new European battery l...            2
157  DHL Supply Chain Breaks Ground on European Bat...            2
260                     Sustainable with GoGreen | DHL            2
263             DHL Group's 2024 Sustainability Report            2
257   How DHL Freight is Positioned for ISO 14001:2026            2

In [40]:
dhl_df = combined_df[
    combined_df["clean_text"].apply(is_relevant)
].copy()

In [42]:
dhl_df["risk_category"] = (
    dhl_df["clean_text"]
    .apply(classify_risk)
)

In [43]:
#Trend Classification
def classify_trend(text):

    text = str(text).lower()

    if "robot" in text or "automation" in text:
        return "Automation"

    elif "battery" in text:
        return "Battery Logistics"

    elif "renewable" in text or "energy" in text:
        return "Renewable Energy"

    elif "sustainability" in text or "gogreen" in text:
        return "Sustainability"

    elif "ai" in text:
        return "Artificial Intelligence"

    return "Other"

dhl_df["trend_category"] = (
    dhl_df["clean_text"]
    .apply(classify_trend)
)

In [44]:
#Then Build Opportunity Categories
def classify_opportunity(text):

    text = str(text).lower()

    if "energy" in text or "renewable" in text:
        return "Energy Logistics"

    elif "battery" in text:
        return "Battery Supply Chain"

    elif "automation" in text or "robot" in text:
        return "Warehouse Automation"

    elif "ai" in text:
        return "AI Logistics"

    elif "partnership" in text:
        return "Strategic Partnership"

    return "Other"

dhl_df["opportunity_category"] = (
    dhl_df["clean_text"]
    .apply(classify_opportunity)
)

In [45]:
#Then Build Risk Categories
def classify_risk(text):

    text = str(text).lower()

    if "tariff" in text:
        return "Trade Tariff"

    elif "regulation" in text:
        return "Regulatory Risk"

    elif "competition" in text:
        return "Competitive Risk"

    elif "delay" in text or "disruption" in text:
        return "Supply Chain Disruption"

    return "Other"

dhl_df["risk_category"] = (
    dhl_df["clean_text"]
    .apply(classify_risk)
)

In [46]:
print(
    dhl_df["risk_category"]
    .value_counts()
)

risk_category
Other                      230
Trade Tariff                 3
Regulatory Risk              1
Supply Chain Disruption      1
Name: count, dtype: int64